Repository TryItOn-TIO/TryItOn-server-spring, pull requests merged in 2025-06, with the labels that each got.

#4 [feat/product] 로그인 사용자용 상품 목록 및 찜한 상품 조회 기능 구현
  src/main/java/com/tryiton/core/product/controller/ProductDetailController.java
  src/main/java/com/tryiton/core/product/dto/ProductDetailResponseDto.java
  src/main/java/com/tryiton/core/product/dto/ProductVariantDto.java
  src/main/java/com/tryiton/core/product/entity/Product.java
  src/main/java/com/tryiton/core/product/service/ProductService.java
  src/main/java/com/tryiton/core/wishlist/service/WishlistService.java
Labels: 🔮 feat

#8 [feat/auth] 회원가입, 로그인 구현
  README.md
  build.gradle
  img.png
  src/main/java/com/tryiton/core/auth/email/controller/EmailAuthController.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailRequestDto.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailSigninRequestDto.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailSigninResponseDto.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailSignupRequestDto.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailSignupResponseDto.java
  src/main/java/com/tryiton/core/auth/email/dto/EmailVerifyRequestDto.java
  src/main/java/com/tryiton/core/auth/email/entity/EmailVerification.java
  src/main/java/com/tryiton/core/auth/email/repository/EmailVerificationRepository.java
  src/main/java/com/tryiton/core/auth/email/service/EmailAuthService.java
  src/main/java/com/tryiton/core/auth/email/service/EmailService.java
  src/main/java/com/tryiton/core/auth/email/util/RandomCodeGenerator.java
  src/main/java/com/tryiton/core/auth/email/util/Validator.java
  src/main/java/com/tryiton/core/auth/jwt/JwtAuthFilter.java
  src/main/java/com/tryiton/core/auth/jwt/JwtUtil.java
  src/main/java/com/tryiton/core/auth/oauth/controller/GoogleAuthController.java
  src/main/java/com/tryiton/core/auth/oauth/dto/GoogleInfoDto.java
  src/main/java/com/tryiton/core/auth/oauth/dto/GoogleSigninRequestDto.java
  src/main/java/com/tryiton/core/auth/oauth/dto/GoogleSignupRequestDto.java
  src/main/java/com/tryiton/core/auth/oauth/dto/GoogleSignupResponseDto.java
  src/main/java/com/tryiton/core/auth/oauth/entity/OauthCredentials.java
  src/main/java/com/tryiton/core/auth/oauth/service/AuthService.java
  src/main/java/com/tryiton/core/auth/security/CustomUserDetailService.java
  src/main/java/com/tryiton/core/auth/security/CustomUserDetails.java
  src/main/java/com/tryiton/core/auth/security/SecurityConfig.java
  src/main/java/com/tryiton/core/common/enums/AuthProvider.java
  src/main/java/com/tryiton/core/common/enums/Gender.java
  src/main/java/com/tryiton/core/common/enums/Style.java
  src/main/java/com/tryiton/core/common/enums/UserRole.java
  src/main/java/com/tryiton/core/common/exception/BusinessException.java
  src/main/java/com/tryiton/core/config/MailConfig.java
  src/main/java/com/tryiton/core/config/WebConfig.java
  src/main/java/com/tryiton/core/member/controller/MemberController.java
  src/main/java/com/tryiton/core/member/dto/SigninRequestDto.java
  src/main/java/com/tryiton/core/member/dto/SigninResponseDto.java
  src/main/java/com/tryiton/core/member/dto/SignupRequestDto.java
  src/main/java/com/tryiton/core/member/dto/SignupResponseDto.java
  src/main/java/com/tryiton/core/member/entity/Member.java
  src/main/java/com/tryiton/core/member/entity/Profile.java
  src/main/java/com/tryiton/core/member/repository/MemberRepository.java
  src/main/java/com/tryiton/core/member/service/MemberService.java
  src/main/resources/application.properties
Labels: 🔮 feat

#15 [refactor/product] 메인페이지에서 랭킹 상품 응답에서 페이징 제거 후 리스트 형태로 변경
  src/main/java/com/tryiton/core/product/controller/ProductController.java
  src/main/java/com/tryiton/core/product/dto/MainProductResponse.java
  src/main/java/com/tryiton/core/product/repository/ProductRepository.java
  src/main/java/com/tryiton/core/product/service/ProductService.java
Labels: 🔧 refactor

#21 [refactor/product] liked 여부를 상품 상세 조회 응답에도 포함
  src/main/java/com/tryiton/core/product/controller/ProductDetailController.java
  src/main/java/com/tryiton/core/product/dto/ProductDetailResponseDto.java
  src/main/java/com/tryiton/core/product/service/ProductService.java
Labels: 🔧 refactor

#23 chore: AWS 설정 추가
  src/main/resources/application-local.properties
Labels: ⚙️ chore
