Repository TryItOn-TIO/TryItOn-server-spring, pull requests merged in 2025-07, with the labels that each got.

#37 fix: EC2 서버 중단 해소 #36
  .github/workflows/deploy.yml
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: 🛠️ fix

#51 [refactor/avatar] 아바타 정보 조회 API 수정
  src/main/java/com/tryiton/core/avatar/controller/AvatarController.java
  src/main/java/com/tryiton/core/avatar/dto/AvatarProductInfoDto.java
  src/main/java/com/tryiton/core/avatar/service/AvatarServiceImpl.java
Labels: 🔧 refactor

#52 [fix/product] 카테고리 API 에러 해결
  src/main/java/com/tryiton/core/product/controller/ProductController.java
  src/main/java/com/tryiton/core/product/dto/CategoryProductResponse.java
  src/main/java/com/tryiton/core/product/repository/CategoryRepository.java
  src/main/java/com/tryiton/core/product/repository/ProductRepository.java
  src/main/java/com/tryiton/core/product/service/CategoryService.java
  src/main/java/com/tryiton/core/product/service/ProductService.java
Labels: 🛠️ fix

#53 [feat/story] 스토리 기능 추가
  src/main/java/com/tryiton/core/auth/email/controller/EmailAuthController.java
  src/main/java/com/tryiton/core/auth/email/service/EmailAuthService.java
  src/main/java/com/tryiton/core/auth/jwt/JwtUtil.java
  src/main/java/com/tryiton/core/auth/security/SecurityConfig.java
  src/main/java/com/tryiton/core/common/enums/StorySort.java
  src/main/java/com/tryiton/core/member/entity/Member.java
  src/main/java/com/tryiton/core/product/controller/ProductDetailController.java
  src/main/java/com/tryiton/core/story/controller/CommentController.java
  src/main/java/com/tryiton/core/story/controller/StoryController.java
  src/main/java/com/tryiton/core/story/controller/StoryLikeController.java
  src/main/java/com/tryiton/core/story/dto/AuthorDto.java
  src/main/java/com/tryiton/core/story/dto/CommentRequestDto.java
  src/main/java/com/tryiton/core/story/dto/CommentResponseDto.java
  src/main/java/com/tryiton/core/story/dto/PositionDto.java
  src/main/java/com/tryiton/core/story/dto/StoriesResponseDto.java
  src/main/java/com/tryiton/core/story/dto/StoryPutDto.java
  src/main/java/com/tryiton/core/story/dto/StoryRequestDto.java
  src/main/java/com/tryiton/core/story/dto/StoryResponseDto.java
  src/main/java/com/tryiton/core/story/entity/Comment.java
  src/main/java/com/tryiton/core/story/entity/Story.java
  src/main/java/com/tryiton/core/story/entity/StoryLike.java
  src/main/java/com/tryiton/core/story/repository/CommentRepository.java
  src/main/java/com/tryiton/core/story/repository/StoryLikeRepository.java
  src/main/java/com/tryiton/core/story/repository/StoryRepository.java
  src/main/java/com/tryiton/core/story/service/CommentService.java
  src/main/java/com/tryiton/core/story/service/StoryLikeService.java
  src/main/java/com/tryiton/core/story/service/StoryService.java
  src/main/java/com/tryiton/core/wishlist/repository/WishlistRepository.java
Labels: 🔮 feat

#55 [fix/closet] Closet 로직의 avatar 정보 처리 수정
  src/main/java/com/tryiton/core/avatar/entity/Avatar.java
  src/main/java/com/tryiton/core/closet/controller/ClosetAvatarController.java
  src/main/java/com/tryiton/core/closet/dto/ClosetAvatarSaveRequestDto.java
  src/main/java/com/tryiton/core/closet/entity/ClosetAvatarItem.java
  src/main/java/com/tryiton/core/closet/service/ClosetAvatarService.java
Labels: 🛠️ fix

#67 fix: 회원가입시 잘못 참조되던 프로필 이미지 변경
  src/main/java/com/tryiton/core/auth/oauth/service/AuthService.java
Labels: 🛠️ fix

#75 [refactor] 옷장에 아바타를 추가하는 기능의 서비스 로직 수정
  src/main/java/com/tryiton/core/closet/controller/ClosetAvatarController.java
  src/main/java/com/tryiton/core/closet/service/ClosetAvatarService.java
  src/test/java/com/tryiton/core/closet/service/ClosetAvatarServiceTest.java
Labels: 🔧 refactor

#78 [fix/story] 비로그인 유저도 스토리를 조회할 수 있도록 수정
  src/main/java/com/tryiton/core/auth/security/SecurityConfig.java
  src/main/java/com/tryiton/core/story/controller/StoryController.java
  src/main/java/com/tryiton/core/story/service/StoryService.java
Labels: 🛠️ fix

#88 fix: AWS 내부 서비스이므로 호스트 이름 검증 비활성화(동적으로 IP 변경 가능성 고려)
  src/main/resources/application-dev.properties
Labels: 🛠️ fix

#91 fix: product 테이블 create_at 컬럼명 수정
  src/main/java/com/tryiton/core/product/repository/ProductRepository.java
Labels: 🛠️ fix

#92 fix: product 테이블의 create_at 컬럼명에 따라 쿼리문 수정
  src/main/java/com/tryiton/core/product/dto/ProductResponseDto.java
  src/main/java/com/tryiton/core/product/entity/Product.java
  src/main/java/com/tryiton/core/product/repository/ProductRepository.java
  src/main/java/com/tryiton/core/story/entity/Story.java
  src/main/java/com/tryiton/core/story/repository/StoryRepository.java
Labels: 🛠️ fix

#93 fix: AWS Lambda 로그 추가
  src/main/java/com/tryiton/core/product/entity/Product.java
  src/main/java/com/tryiton/core/recommend/service/PersonalizedService.java
  src/main/resources/application-local.properties
Labels: 🧪 test

#95 fix: build 에러 수정 #64
  src/main/java/com/tryiton/core/recommend/dto/LambdaProductDto.java
Labels: 🛠️ fix

#98 [feat/recommend] Lambda response 타입에 맞게 재정의
  src/main/java/com/tryiton/core/recommend/dto/LambdaBatchDto.java
  src/main/java/com/tryiton/core/recommend/service/RecommendationService.java
Labels: 🛠️ fix

#99 fix: ProductRepositoy N+1 문제 방지 로직 추가
  src/main/java/com/tryiton/core/product/repository/ProductRepository.java
  src/main/java/com/tryiton/core/recommend/service/RecommendationService.java
Labels: 🛠️ fix

#100 fix: JWT 토큰으로 사용자 맞춤 컨트롤러 처리 #64
  src/main/java/com/tryiton/core/recommend/controller/RecommendationController.java
Labels: 🛠️ fix

#105 [fix/recommend] 인기상품, 연령대별 인기상품, 유사상품 로그인 유저 컬럼 반영
  src/main/java/com/tryiton/core/recommend/controller/RecommendationController.java
  src/main/java/com/tryiton/core/recommend/service/RecommendationService.java
Labels: 🛠️ fix

#121 [Fix/wishlist] 카테고리별로 찜 상품 조회
  src/main/java/com/tryiton/core/wishlist/controller/WishlistController.java
  src/main/java/com/tryiton/core/wishlist/repository/WishlistItemRepository.java
  src/main/java/com/tryiton/core/wishlist/service/WishlistService.java
Labels: 🛠️ fix
